### ISSUE TITLE
where is the main function?

### ISSUE THREAD

**Issue by leoge0113** [wizzardo/epoll#2]
how the code working?If it is a progress ,where is the main function?

**Comment by wizzardo** [comment]
sorry, I don't get the question. It's a socket-server based on epoll events, main logic is in C, I call it from java by jni

**Comment by leoge0113** [comment]
Thank u for your explain about the code "java call c by jni".
But where is the main(String args[]) function?

**Comment by wizzardo** [comment]
there is no 'main' function, it's a library, not an application. You can use it like in example in readme
