### ISSUE TITLE
How to wake up an epfd ?

### ISSUE THREAD

**Issue by kyle2008** [wizzardo/epoll#4]
How to wake up an epfd when the epfd is doing waitForEvents(...)?

**Comment by kyle2008** [comment]
> the thread called waitForEvents() is waiting for new io events (read/write/accept/close), you can pass amount of ms in waitForEvents as a timeout, so why do you want to wake up that thread?

not all handle are in io thread,  if we write from other thread in to io thread, we may need to wake the io thread .

**Comment by wizzardo** [comment]
other thread can just write into connection, it doesn't need to wake up IOThread, you only need to pass ByteBufferProvider to connection.write(ByteBufferProvider bufferProvider)

**Comment by kyle2008** [comment]
So you lock the connection’s buffer and then write the data into this buffer? And then write to fd in other thread?

**Comment by wizzardo** [comment]
write(ReadableData readable, ByteBufferProvider bufferProvider) will use ByteBufferProvider as a temporal storage in native memory to write data to fd. If not all the data will be written at once then it will be stored in a connection's queue, IOThread will receive an 'onWrite' event and will write the remaining data. So connection.write(...) is thread-safe if you use thread-local ByteBufferProvider

**Comment by kyle2008** [comment]
This days I try to learn cpp and epoll ,i see others framework write an value to eventfd  that added to epfd ,to wake up the epfd, for example I write data to connection in other thread,if the data will write to remote immediately or after sleep 500ms ?

**Comment by wizzardo** [comment]
immediately, default timeout of 500ms required to wake up IOThread to check that server is not stopped and to process timeouts

**Comment by kyle2008** [comment]
Thanks for your patience：）
